[tox]
requires =
    tox>=4.2
env_list = py3-ansible
skipsdist = true

[testenv]
description = "tox virtual env for Ansible 10 with molecule for podman"
deps =
    ansible==10.2.*
    ansible-lint==24.7.*
    molecule==24.7.*
    molecule-plugins[podman]==23.5.*
    paramiko==3.*
    yamllint==1.35.*
commands = 
    pip check
    pip list
setenv =
    TOX_ENVNAME={envname}
    PY_COLORS=1
    ANSIBLE_FORCE_COLOR=1
