---

- name: Apply Node Exporter role
  become: true
  become_method: sudo
  become_user: root
  hosts:
    - lxc-nodeexporter
    - k3s
  roles:
    - name: nodeexporter
      tags: nodeexporter

- name: Apply PVE Exporter role
  hosts: lxc-pveexporter
  roles:
    - name: pveexporter
      tags: pveexporter
      vars:
        pve_exporter_token_name: "pveexporter"
        pve_exporter_token_value: "fce38aea-236a-4d0b-9f29-561a90629537"
