#cloud-config

hostname: infra01
manage_etc_hosts: true
power_state: {mode: reboot}

allow_public_ssh_keys: true
ssh_quiet_keygen: true

users:
  - name: user
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEHKEQ6FLrn8b85ClMxvu04DbAiyMZ5tf5ktL4xEpSZ mettmett@JH-LVL10
    plain_text_passwd: pouetpouet

# Misc settings
timezone: Europe/Paris
locale: en_US

package_update: true
package_upgrade: true
packages:
  - cockpit
  - docker.io
  - docker-compose-v2
  - libusb-1.0-0-dev
  - nut
  - qemu-guest-agent
  - systemd-timesyncd
  - ufw

runcmd:
  - rm -f /etc/machine-id
  - systemd-machine-id-setup
  - rm -f /var/lib/dbus/machine-id
  - ln -s /etc/machine-id /var/lib/dbus/machine-id
  - echo '$(openssl rand -base64 32)' > /var/lib/cloud/seed/random-seed
  - systemctl enable qemu-guest-agent
  - systemctl enable cockpit.service
  - systemctl enable docker.service
  # DEBUT // NUT configuration
  - mv /etc/nut/upsd.users /etc/nut/upsd.users.doc
  - sed -i 's/MODE=none/MODE=standalone/' /etc/nut/nut.conf
  - echo -e "[admin]\npassword = your_password\nactions = SET\ninstcmds = ALL\nupsmon master" >> /etc/nut/upsd.users
  - echo "NOTIFYCMD /usr/sbin/upssched" >> /etc/nut/upsmon.conf
  - echo "MONITOR nutdev1@localhost 1 admin pouetpouet master" >> /etc/nut/upsmon.conf
  # FIN // NUT configuration
  - ufw allow 22/tcp
  - ufw allow 8080/tcp
  - ufw allow 9090/tcp
  # DEBUT // Docker configuration
  - docker network create --driver=bridge frontend
  - mkdir -p /opt/docker
  # FIN // Docker configuration
  - ufw enable
  - echo "done" > /tmp/cloud-config.done

write_files:
  - path: /etc/nut/ups.conf
    content: |
      maxretry = 3
      [nutdev1]
        driver = "usbhid-ups"
        port = "auto"
        vendorid = "0463"
        productid = "FFFF"
        product = "Eaton 3S"
        vendor = "EATON"
        bus = "009"
        device = "002"
        busport = "001"

  - path: /etc/nut/upsd.users
    content: |
      [admin]
      password = pouetpouet
      actions = SET
      instcmds = ALL
      upsmon master

  - path: /opt/docker/.env
    content: |
      IPAM_DATABASE_PASS=Grooving24Depletion58Improving96Uphold6
      MYSQL_ROOT_PASSWORD=Naturist12Rickety56Graceless26Molar

  - path: /opt/docker/phpipam.yml
    content: |
      ---
      services:
        phpipam-web:
          image: phpipam/phpipam-www:1.7x
          ports:
            - "8080:80/tcp"
          environment:
            - TZ=Europe/Paris
            - IPAM_DATABASE_HOST=phpipam-mariadb
            - IPAM_DATABASE_USER=phpipamdbuser
            - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
            - IPAM_DATABASE_NAME=phpipamdb
            - IPAM_DATABASE_WEBHOST=%
            #- IPAM_DISABLE_INSTALLER=true
            # ** Please disable installation helper scripts by setting IPAM_DISABLE_INSTALLER = 1 after initial setup is complete.
            - OFFLINE_MODE=true
            #- IPAM_FOOTER_MESSAGE=""
          restart: unless-stopped
          networks:
            - frontend
            - backend
          volumes:
            - phpipam-data:/phpipam
            # - phpipam-ca:/usr/local/share/ca-certificates:ro
          depends_on:
            - phpipam-mariadb

        phpipam-cron:
          image: phpipam/phpipam-cron:1.7x
          environment:
            - TZ=Europe/Paris
            - IPAM_DATABASE_HOST=phpipam-mariadb
            - IPAM_DATABASE_USER=phpipamdbuser
            - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
            - IPAM_DATABASE_NAME=phpipamdb
            - SCAN_INTERVAL=1h
          restart: unless-stopped
          # volumes:
            # - phpipam-ca:/usr/local/share/ca-certificates:ro
          networks:
            - backend
          depends_on:
            - phpipam-mariadb

        phpipam-mariadb:
          image: mariadb:lts-noble
          environment:
            - MYSQL_USER=phpipamdbuser
            - MYSQL_PASSWORD=${IPAM_DATABASE_PASS}
            # - MYSQL_DATABASE=phpipamdb
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          restart: unless-stopped
          networks:
            - backend
          volumes:
            - phpipam-db-data:/var/lib/mysql

      volumes:
        phpipam-data:
        phpipam-db-data:
        # phpipam-logo:
        # phpipam-ca:

      networks:
        frontend:
          external: true
        backend:
