apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: test-web
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webserver
    spec:
      serviceAccountName: test-web-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: webserver
        image: nginxinc/nginx-unprivileged:alpine
        ports:
        - containerPort: 80
          name: web
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
      nodeSelector:
        topology.kubernetes.io/usage: "general"
