apiVersion: v1
kind: Secret
metadata:
  name: grafana-s3-credentials
  namespace: monitoring
type: Opaque
data:
  access_key: WkNQaUo4WnB5YnVBQUpOR1g1SEYK
  admin_password: U2xlZDQtTWFub3I3LVZpc29yNC1PcHByZXNzZWQyLVN0dW1wMwo=
  secret_key: aFNOUjRleTV1SUp3YW1TZ2hwcFVwMUZYWE0wRTZxUHNTOXd2dGNIRAo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: grafana
        image: grafana/grafana-oss:11.5.2
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "amhvZ3JhZmFuYWFkbWluCg=="
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-s3-credentials
              key: admin_password
        - name: GF_PATHS_DATA
          value: "/var/lib/grafana"
        - name: GF_AWS_BUCKET
          value: "grafana-data"
        - name: GF_AWS_REGION
          value: "fr-ouest-1"
        - name: GF_AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: grafana-aws-credentials
              key: access_key
        - name: GF_AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: grafana-aws-credentials
              key: secret_key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsUser: 472
          runAsGroup: 472
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        emptyDir: {}
