apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "sleep", "3600" ]  # Keeps the container running for testing
      volumeMounts:
        - mountPath: "/mnt/nfs"
          name: nfs-volume
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
