#cloud-config

hostname: charger
manage_etc_hosts: true

allow_public_ssh_keys: true
ssh_quiet_keygen: true

users:
  - name: root
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEHKEQ6FLrn8b85ClMxvu04DbAiyMZ5tf5ktL4xEpSZ mettmett@JH-LVL10

  - name: jhoadmin
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEHKEQ6FLrn8b85ClMxvu04DbAiyMZ5tf5ktL4xEpSZ mettmett@JH-LVL10
    passwd: $6$rounds=500000$tAy4OxDkBy61IO3n$qMZ5IBOoMUvXAgIB4PYkaZzZlalE4Ez0XOb9AYP1dCyK9WsxE4ySFLd2HacSdgaPLakcks5bGmDVo/r7O0H9r1

# Misc settings
timezone: Europe/Paris
locale: en_US.UTF-8

# Disk setup
resize_rootfs: noblock
disk_setup:
  /dev/sdb: {table_type: mbr, layout: true, overwrite: true}
fs_setup:
- {device: /dev/sdb1, filesystem: ext4, label: data1}
mounts:
- [ /dev/sdb1, /mnt/nfs, 'ext4', 'defaults', '0', '2' ]

runcmd:
  - rm -f /etc/machine-id
  - rm -f /var/lib/dbus/machine-id
  - ln -s /etc/machine-id /var/lib/dbus/machine-id
  - pacman -Syu --noconfirm bash-completion cloud-guest-utils extra/cockpit curl extra/cockpit-storaged less libiscsi libusb nano extra/netdata extra/nut pcp qemu-guest-agent udisks2-btrfs vim

  # DEBUT // Installation et configuration NFS server
  - pacman -S --noconfirm nfs-utils
  - mount -a
  - mkdir -p /mnt/nfs/gitea
  - mkdir -p /mnt/nfs/vault
  - mkdir -p /mnt/nfs/kubernetes
  - chmod -R 750 /mnt/nfs
  - chown -R nobody:nobody /srv/mnt
  - chown -R root:root /srv/nfs/kubernetes
  - echo "/mnt/nfs/gitea 192.168.1.0/24(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
  - echo "/mnt/nfs/vault 192.168.1.0/24(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
  - echo "/mnt/nfs/kubernetes 192.168.1.21/24(rw,sync,no_subtree_check,no_root_squash) 192.168.1.22/24(rw,sync,no_subtree_check,no_root_squash) 192.168.1.23/24(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
  - exportfs -arv
  # FIN // Installation et configuration NFS server

  - rm /etc/motd.d/cockpit /etc/issue.d/cockpit.issue
  - systemctl enable --now --all cockpit.socket netdata.service nut-driver-enumerator.service nfs-server.service
  - reboot
